In [2]:
import pandas as pd
import numpy as np
import matplotlib .pyplot as plt
from sklearn.datasets import load_boston
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score

In [3]:
dataset = load_boston()
x_full, y_full=dataset.data,dataset.target
n_samples = x_full.shape[0]
n_features = x_full.shape[1]

In [4]:
type(y_full)

numpy.ndarray

In [5]:
pd.DataFrame(x_full)

0     1      2    3      4      5     6       7    8      9    10  \
0    0.00632  18.0   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1    0.02731   0.0   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2    0.02729   0.0   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3    0.03237   0.0   2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4    0.06905   0.0   2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   
..       ...   ...    ...  ...    ...    ...   ...     ...  ...    ...   ...   
501  0.06263   0.0  11.93  0.0  0.573  6.593  69.1  2.4786  1.0  273.0  21.0   
502  0.04527   0.0  11.93  0.0  0.573  6.120  76.7  2.2875  1.0  273.0  21.0   
503  0.06076   0.0  11.93  0.0  0.573  6.976  91.0  2.1675  1.0  273.0  21.0   
504  0.10959   0.0  11.93  0.0  0.573  6.794  89.3  2.3889  1.0  273.0  21.0   
505  0.04741   0.0  11.93  0.0  0.573  6.030  80.8  2.5050  1.0  273.0  21.0   

         11    12  
0    396.90  4.98  
1    396.90  9.14  
2    392.83  4.03  
3    394.63  2.94  
4    396.90  5.33  
..      ...   ...  
501  391.99  9.67  
502  396.90  9.08  
503  396.90  5.64  
504  393.45  6.48  
505  396.90  7.88  

[506 rows x 13 columns]

In [6]:
rng = np.random.RandomState(0)
missing_rate=0.5
n_missing_samples = int(np.floor(n_samples*n_features*missing_rate))

In [7]:
missing_features = rng.randint(0,n_features,n_missing_samples)
missing_samples = rng.randint(0,n_samples,n_missing_samples)

In [8]:
x_missing = x_full.copy()
y_missing = y_full.copy()
x_missing[missing_samples,missing_features]=np.nan
x_missing = pd.DataFrame(x_missing)

In [9]:
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
x_missing_mean=imp_mean.fit_transform(x_missing)

In [10]:
imp_0 = SimpleImputer(missing_values=np.nan,strategy='constant',fill_value=0)
x_missing_value=imp_0.fit_transform(x_missing)

In [11]:
x_missing_reg = x_missing.copy()

In [12]:
sortindex = np.argsort(x_missing_reg.isnull().sum(axis=0)).values

In [13]:
df = x_missing_reg

In [14]:
type(df)

pandas.core.frame.DataFrame

In [15]:
fillc = df.iloc[:,6]

In [16]:
type(fillc)

pandas.core.series.Series

In [17]:
df = pd.concat([df.iloc[:,df.columns != 6],pd.DataFrame(y_full)],axis=1)

In [18]:
df_0 = SimpleImputer(missing_values=np.nan,strategy='constant',fill_value=0).fit_transform(df)

In [19]:
y_train=fillc[fillc.notnull()]

In [20]:
y_train

0      65.2
1      78.9
2      61.1
3      45.8
5      58.7
       ... 
500    79.7
501    69.1
502    76.7
503    91.0
504    89.3
Name: 6, Length: 321, dtype: float64

In [35]:
df = pd.DataFrame(np.random.randint(0,10,size=12).reshape((3,4)),index = ['one', 'two', 'three'], columns= list('abcd'))

In [51]:
df.drop('a', axis=1)

b  c  d
one    2  4  5
two    4  0  7
three  9  5  2

In [52]:
df1 = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
                   'key2' : ['one', 'two', 'one', 'two', 'one'],
                   'data1' : np.random.randn(5),
                   'data2' : np.random.randn(5)})


In [53]:
df1

key1 key2     data1     data2
0    a  one -0.040577  0.104622
1    a  two  1.594205 -0.293377
2    b  one -2.446552 -1.008319
3    b  two -1.302909  0.791124
4    a  one  1.481858 -0.926229

In [61]:
for name,group in df1.groupby([df1['key1']],axis=0):
    print(name)
    print(group)

a
  key1 key2     data1     data2
0    a  one -0.040577  0.104622
1    a  two  1.594205 -0.293377
4    a  one  1.481858 -0.926229
b
  key1 key2     data1     data2
2    b  one -2.446552 -1.008319
3    b  two -1.302909  0.791124


In [76]:
df = pd.DataFrame(np.random.randint(1,23,size=24).reshape((8,3)),index=list("12345678"),columns=list('abc'))

In [77]:
df

a   b   c
1   2  14   8
2   5  20   9
3   6  16  12
4   5  20  11
5  10  17  11
6   4  14  22
7  21  15   7
8  10  13  15

In [78]:
# 归一化练习
from sklearn.preprocessing import MinMaxScaler

In [79]:
scaler = MinMaxScaler()
scaler = scaler.fit_transform(df)

In [80]:
scaler

array([[0.        , 0.14285714, 0.06666667],
       [0.15789474, 1.        , 0.13333333],
       [0.21052632, 0.42857143, 0.33333333],
       [0.15789474, 1.        , 0.26666667],
       [0.42105263, 0.57142857, 0.26666667],
       [0.10526316, 0.14285714, 1.        ],
       [1.        , 0.28571429, 0.        ],
       [0.42105263, 0.        , 0.53333333]])

In [81]:
df = pd.DataFrame(scaler)

0         1         2
0  0.000000  0.142857  0.066667
1  0.157895  1.000000  0.133333
2  0.210526  0.428571  0.333333
3  0.157895  1.000000  0.266667
4  0.421053  0.571429  0.266667
5  0.105263  0.142857  1.000000
6  1.000000  0.285714  0.000000
7  0.421053  0.000000  0.533333

In [89]:
df.iloc[[2],[1]] = np.nan

In [91]:
df

a     b   c
1   2  14.0   8
2   5  20.0   9
3   6   NaN  12
4   5  20.0  11
5  10  17.0  11
6   4  14.0  22
7  21  15.0   7
8  10  13.0  15

In [96]:
df.dropna(subset=['b'])

a     b   c
1   2  14.0   8
2   5  20.0   9
4   5  20.0  11
5  10  17.0  11
6   4  14.0  22
7  21  15.0   7
8  10  13.0  15

In [94]:
df1

a     b   c
1   2  14.0   8
2   5  20.0   9
3   6   NaN  12
4   5  20.0  11
5  10  17.0  11
6   4  14.0  22
7  21  15.0   7
8  10  13.0  15

In [2]:
a = 1
b = []
for i in range(13):
    a = 1 + i*4
    b.append(a)
    
print(b)

[1, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49]


In [3]:
sum(b)

325

In [16]:
import numpy as np
np.linspace(1,11,3,endpoint=True,retstep=True)

(array([ 1.,  6., 11.]), 5.0)

In [11]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [12]:
sum(np.arange(1,49,4))

276

In [13]:
np.arange(1,49,4)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45])